version: "3.9"

services:
  app:
    build: .
    container_name: spring_app
    ports:
      - "8080:8080"
    volumes:            # Remove later once done with development
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: mvn spring-boot:run
    depends_on:
      - ollama
    environment:
      SPRING_AI_OLLAMA_BASE_URL: http://ollama:11434

  ollama:
    image: ollama/ollama:latest
    container_name: ollama_ai
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
    entrypoint: >
      sh -c "ollama pull qwen2.5:7b && ollama serve"

volumes:
  ollama_data:
